# ─────────────────────────────────────────────────────────────────────────────
# PRODUCTION PROFILE
# ─────────────────────────────────────────────────────────────────────────────

# AI / LLM
ai.api.key=ENC(Jzys/WwUdF99jO7l2v0eanb+PI1SQOLlhipPo+htmlYNMeb04TqGN+gTajEPvptpNeFdlHJ8qr8szaJ23P5Qfz+ogSB1lpYE1QuyJoZVW/0FNqTuCpDEFPoRABsB1YGD)

# Supabase
supabase.url=ENC(AklqAV4+tLjX79NA7ND8YCfPr7+qsOMKa/OT4Sj/x+58625H5R7KA+oUxytId2fE74zHbg7pr0zM0/A+NzN9UD0qHlzsYVakG38Ps5yfL4Y=)
supabase.storage.endpoint=ENC(aOM5inCtsVXrn63zAjmDpJ3WOzpwCeewe5ZbOe8RMMAa+zkR4ZTPcVpk7OjUt10hNTpaYZiZi28tSChfG+ocxoYRGRyrTZ04Q/hbafRgMT2kfOSVazpJWJVAvV51GnX7)
supabase.storage.region=eu-north-1
supabase.storage.access-key=ENC(h2M+IFHhwx3LvbDXcX1PUTVMor/1YsJJfC3/l1LcepULYokx/AtU7u36uDa5UROu7PFdOLocBfSsSZ087KFvC+LcFiJeq5REv4V/V2CQayE=)
supabase.storage.secret-key=ENC(gMWXjjGIHB+N1vXAzp+seui8r9D59f8ltOu/M41C96RiMOSYj7DnnhOcL43pXXxl2J1o4f5UY3lxZ5E0Gtr5ns4ynUdyzYPMFKdHUZTMxyjTsPMRdc9lWqXzvuVZh6uEDjwkRhVX27F8ObvCvGhJJw==)

# PostgreSQL
spring.datasource.url=ENC(BOL6DDPKWeefSp/IYxE0PEPqASBFxhz7+lRHHWB2hd+vko5mZ+22JADzkPSjDO3/QInBaarQhJdEUIb7FXGsrdpsmOBRnW4SnXzki5SAMk8Rk6OHX96cJT1SvcTHgujMQ7NPdWllPmz3ziX9mRthtg==)
spring.datasource.username=postgres
spring.datasource.password=ENC(W7D0RCrUiW9HUtn7puLQvLkz/Qx1S7UZERyiSIuhe4PAQaY83OOS0PNdnkp7C26VkaidxevQhDA1iASD88q/OA==)
spring.jpa.hibernate.ddl-auto=update

# Redis (Upstash)
redis.url=ENC(PBGoH0FJa1RcqsKhkLP+uREx/pVslM7IeLBmePuGnb/qABnHOULLcnaY/r+Su8ogsfy60SqfsSYyLcovKWozgU+u/dZg7EMXqohYWy6dohgFqKh19wmCy2QfUQ7S2bhmivhH5etS2MP338Nl4KSMIaMxok+v4bORCrfNWiKEDsHNiT1I6BKyCnVtCxW1m6k+mwbzG+cGk0EE43kQEh006g==)

# CORS
app.cors.allowed-origins=https://resume-studio-frontend.vercel.app/