# ─────────────────────────────────────────────────────────────────────────────
# LOCAL PROFILE
# ─────────────────────────────────────────────────────────────────────────────

# AI / LLM
ai.api.key=ENC(xfW+pS/f4EaCFWWqp5UIGl4efBEtLd+mboqxBdtqSmOJce+rnE4u6ROE2oNy2d0sSnOCtPOmpch4AHx2N4Fya06uzm+iEX8q2kdsB39XXa94itiB0wzcAcj/ufcjg3QW)

# Supabase
supabase.url=ENC(WoybJGpxMJRVYjg9+Y5u7cCG69cIF0oV3zWSkQD4ecb5IX/tUZx1kXg/nYVqPbU0XW/AxGL1QfHc1gGyN0KnwQiH5ar0IE6ooQxJ4Sv48J8=)
supabase.storage.endpoint=ENC(x03GyGKb4bcGOo+lzq8JTwDZl4yfYLJjw+sYfR6jlY8x5XTg0NYMKSRmu1OlXI+PB485Cpl7htNma/A0rgIkFQtguwVe2QRUb0omLBsIp4Muqb2l8vG2vZ5VuatMd1lG)
supabase.storage.region=eu-central-1
supabase.storage.access-key=ENC(BB6UA03Ia9waqo6xBLl0lBIlvz96unfvtxifXXRCaCAaakAfe2+jfZBOyuccTmvBYP3WpcCmDI88Pv7uZh0ndJSfjKJ4E9ITiWpP7W0P0xc=)
supabase.storage.secret-key=ENC(ou6ox/C6O1W1WNBsZVYqdudeaDmC4SzLS1LmT1aaS2gvvdiI8d13ZFkf/ilBah2WwL58jKg5wKLYVrNynp+GMQKMBDBiNG2i2p/0HiHybOeh3HW8sKtL2M1BVa9yfCru0lj0AnD4RTkyxcHZO6m9RQ==)

# PostgreSQL
spring.datasource.url=ENC(O1av6+u4RseXeea9UoQ/YSB36NbnhgGatTp0Ts8J5grIQC+DUxZFZ9GQ4WOWKtEU5OgOf5q8SDmkhoxlzYSQIx7DehQiyeGOmbbwC3DKk8tRQtNTKnmlcAB7HSZY4dmfJcwq6r4O6x2bhHULq0kWZg==)
spring.datasource.username=postgres
spring.datasource.password=ENC(QLZk84zR1HS+sGR018OqBLTvkhraQsKGWSoVRWGR1YNsGOMXiqwlY+Ri9swgt9Z+)
spring.jpa.hibernate.ddl-auto=update

# Redis (Upstash)
redis.url=ENC(PBGoH0FJa1RcqsKhkLP+uREx/pVslM7IeLBmePuGnb/qABnHOULLcnaY/r+Su8ogsfy60SqfsSYyLcovKWozgU+u/dZg7EMXqohYWy6dohgFqKh19wmCy2QfUQ7S2bhmivhH5etS2MP338Nl4KSMIaMxok+v4bORCrfNWiKEDsHNiT1I6BKyCnVtCxW1m6k+mwbzG+cGk0EE43kQEh006g==)

# CORS
app.cors.allowed-origins=http://localhost:3000
